"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os
import environ
from backend.settings import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR) + '/.env')    



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.thisamericanlifeapp.parkcrest.dev', 
                 'thisamericanlifeapp.parkcrest.dev', 
                 '127.0.0.1',
                 'localhost',
                 '104.248.49.129']




DATABASES = {
    # dev
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dev-tal', 
        'USER': 'postgres',
        'PASSWORD': env("DEV_DB_PASSWORD"),
        'HOST': env('DEV_DB_HOST'),
        'PORT': env('DEV_DB_PORT'),
    }
}

