# Generated by Django 5.0.1 on 2024-01-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_num', models.IntegerField(primary_key=True, serialize=False)),
                ('episode_title', models.CharField(blank=True, max_length=500)),
                ('episode_date', models.DateField(blank=True, verbose_name='date published')),
                ('episode_audio_url', models.CharField(blank=True, max_length=500)),
                ('episode_descript', models.CharField(blank=True, max_length=500)),
                ('episode_acts', models.JSONField(blank=True)),
            ],
            options={
                'ordering': ['-episode_num'],
            },
        ),
        migrations.CreateModel(
            name='Episode_Link',
            fields=[
                ('episode_link_num', models.IntegerField(primary_key=True, serialize=False)),
                ('episode_link_url', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-episode_link_num'],
            },
        ),
    ]
