# Generated by Django 5.0.1 on 2024-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tal_app', '0002_alter_episode_episode_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode_link',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='episode_link',
            name='episode_link_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='episode_link',
            name='episode_link_url',
            field=models.CharField(max_length=500),
        ),
    ]
