# Generated by Django 5.0.1 on 2024-01-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tal_app', '0003_episode_id_episode_link_id_alter_episode_episode_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-episode_num']},
        ),
        migrations.AlterModelOptions(
            name='episode_link',
            options={'ordering': ['-episode_link_num']},
        ),
    ]
