# Generated by Django 5.0.1 on 2024-01-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tal_app', '0004_alter_episode_options_alter_episode_link_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_acts',
            field=models.JSONField(blank=True, default={'NoActData': 'No act Data.'}),
        ),
    ]
