# Generated by Django 5.0.1 on 2024-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tal_app', '0005_alter_episode_episode_acts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_acts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
